#!/usr/bin/env ruby -wKU
# Make sure rb-appscript is installed
begin
  require "appscript"
rescue LoadError
  puts <<-eof
rb-appscript not installed. Run

gem install rb-appscript

and then trying running this script again
eof
  exit 1
end

if !ARGV.empty? && ARGV.last =~ /^\d+p$/
  height = ARGV.last.to_i
  width  = height * 16 / 9
  name   = ARGV.first if ARGV.size == 2
else
  # Use command line arguments if available, otherwise prompt user
  case ARGV.size
  when 0
    print "Enter width:  "
    width = gets.chomp

    print "Enter height: "
    height = gets.chomp
  when 2
    width, height = ARGV
  when 3
    name, width, height = ARGV
  end
end

width, height = width.to_i, height.to_i

# Get the frontmost process
processes = Appscript.app("System Events").application_processes.get
main_process = firstmost = processes.find { |p| p.frontmost.get }

# Test the name of the frontmost process, ending if it matches the name
# supplied through the command line, or if it's equal to Terminal and we're
# looking for the second frontmost process
if !name.nil?
  if main_process.name.get != name
    main_process = processes.find { |p| p.name.get == name }
  end
elsif firstmost.name.get =~ /terminal/i
  firstmost.visible.set false
  main_process = processes.find { |p| p.frontmost.get }
  firstmost.visible.set true
end

# Attempt to set the position of the top window of the targeted process
top_window = main_process.windows.first
begin
  top_window.position.set [1, 1]
  top_window.size.set [width + 1, height + 1]
rescue Appscript::CommandError
  puts "Could not resize #{main_process.name.get} to #{width}x#{height}"
end
